# Logging
logging:
  ## MDC als Teil des Level-Eintrags
  pattern.level : '%5p [${spring.application.name},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]'
  level:
    org.springframework: INFO
    muenchen.praxis: INFO
#logging.level.org.springframework.security: DEBUG
#logging.level.de.muenchen: DEBUG


spring:
    profiles: local, test
    #DB
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password:
        driverClassName: org.h2.Driver
        poolSize: 30
    #JPA
    jpa:
        database: H2
        show-sql: true
        hibernate:
          ddl-auto: update
        database-platform: org.hibernate.dialect.H2Dialect
flyway:
  baseline-on-migrate: true
  enabled: true
  locations: classpath:/db/migration

