create table answer (answerid integer  generated by default as identity, content varchar(255), value double not null, metri_metricid integer, primary key (answerid));
create table classification (classificationid integer generated by default as identity, description varchar(255), name varchar(255), primary key (classificationid));
create table framework (frameworkid integer generated by default as identity, descriptionfw varchar(255), namefw varchar(255), primary key (frameworkid));
create table framework_evaluation (framework_evaluationid integer generated by default as identity, priority integer, classificationid integer, frameworkid integer, requirementid integer, primary key (framework_evaluationid));
create table metric (metricid integer  generated by default as identity, description varchar(255), primary key (metricid));
create table question (questionid integer generated by default as identity, question varchar(255), metricid integer, require_requirementid integer, primary key (questionid));
create table requirement (requirementid integer generated by default as identity, content varchar(255), classi_classificationid integer, primary key (requirementid));
CREATE TABLE feva_result (feva_resultid integer  generated by default as identity, framework_evaluationid integer, questionid integer, answerid integer, primary key (feva_resultid));