create table answer (answerid integer  generated by default as identity, content varchar(255), value double not null, primary key (answerid));
create table classification (classificationid integer  generated by default as identity, description varchar(255), name varchar(255), primary key (classificationid));
create table classification_requirement_list (classification_classificationid integer not null, requirement_list_requirementid integer not null);
create table framework (frameworkid integer, descriptionfw varchar(255), namefw varchar(255), framework_evaluationid integer, primary key (frameworkid));
create table framework_evaluation (framework_evaluationid integer, priority integer, answerid integer, classificationid integer, frameworkid integer, questionid integer, requirementid integer, primary key (framework_evaluationid));
create table metric (metricid integer  generated by default as identity, description varchar(255), primary key (metricid));
create table metric_answer_list (metric_metricid integer not null, answer_list_answerid integer not null);
create table question (questionid integer generated by default as identity, question varchar(255), metricid integer, primary key (questionid));
create table requirement (requirementid integer generated by default as identity, content varchar(255), primary key (requirementid));
create table requirement_question_list (requirement_requirementid integer not null, question_list_questionid integer not null);

-- Eventuell bei Problemen mögliche Ursache
--alter table classification_requirement_list add constraint FK5lf7sr339yhd6rbl27pahrp09 foreign key (classification_classificationid) references classification;
--alter table metric_answer_list add constraint FKpffowiviamald0f85njupodan foreign key (metric_metricid) references metric;